apiVersion: v1
kind: Service
metadata:
  name: nodeport-lab2-app2
spec:
  type: NodePort
  selector:
   app: nodeport-lab2-app2
  ports:
   - port: 8070
     targetPort: 8070
     nodePort: 31311 #(30000-32767)
     protocol: TCP