apiVersion: v1
kind: Pod
metadata:
  name: lab2-app2
  labels:
    name: lab2-app2
spec:
  containers:
  - name: lab2-app2
    image:  lab2-app2
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8070
        type: NodePort
        nodePort: 31311
